# Deploy Feature Branch Preview to main branch previews subfolder
name: Deploy Feature Branch Preview to Main Branch

on:
  push:
    branches:
      - 'feature/*'
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set write permissions

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Extract feature name
        id: extract
        run: echo "FEATURE_NAME=${GITHUB_REF#refs/heads/feature/}" >> $GITHUB_ENV

      - name: Create previews directory if it doesn't exist
        run: mkdir -p previews

      - name: Checkout feature branch to temporary location
        run: |
          mkdir -p /tmp/feature-content
          git worktree add --detach /tmp/feature-content ${{ github.sha }}
          echo "Feature branch content:"
          ls -la /tmp/feature-content/

      - name: Prepare feature branch content for deployment
        shell: bash
        run: |
          mkdir -p previews/${{ env.FEATURE_NAME }}
          rm -rf previews/${{ env.FEATURE_NAME }}/*
          
          rsync -av --exclude 'node_modules' --exclude '.git' --exclude '.github' \
                --exclude 'attribute-selector-structure' \
                /tmp/feature-content/ previews/${{ env.FEATURE_NAME }}/
          
          # Create a preview notice file
          echo "# Preview Environment" > previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "" >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "This is a preview of the \`${{ env.FEATURE_NAME }}\` feature branch." >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "" >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "Last updated: $(date)" >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "" >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          echo "Commit: ${{ github.sha }}" >> previews/${{ env.FEATURE_NAME }}/PREVIEW_NOTICE.md
          
          # Create an index.html if none exists
          if [ ! -f previews/${{ env.FEATURE_NAME }}/index.html ]; then
            # Create a simple index.html file with a preview notice and links
            HTML_FILE=previews/${{ env.FEATURE_NAME }}/index.html
            echo "<!DOCTYPE html>" > $HTML_FILE
            echo "<html lang=\"en\">" >> $HTML_FILE
            echo "<head>" >> $HTML_FILE
            echo "  <meta charset=\"UTF-8\">" >> $HTML_FILE
            echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> $HTML_FILE
            echo "  <title>${{ env.FEATURE_NAME }} Preview</title>" >> $HTML_FILE
            echo "  <style>" >> $HTML_FILE
            echo "    body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; max-width: 800px; margin: 0 auto; }" >> $HTML_FILE
            echo "    h1 { color: #333; }" >> $HTML_FILE
            echo "    .notice { background: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin-bottom: 20px; }" >> $HTML_FILE
            echo "    a { color: #007bff; text-decoration: none; }" >> $HTML_FILE
            echo "    a:hover { text-decoration: underline; }" >> $HTML_FILE
            echo "  </style>" >> $HTML_FILE
            echo "</head>" >> $HTML_FILE
            echo "<body>" >> $HTML_FILE
            echo "  <h1>${{ env.FEATURE_NAME }} Preview</h1>" >> $HTML_FILE
            echo "  <div class=\"notice\">" >> $HTML_FILE
            echo "    <p>This is a preview deployment of the <strong>${{ env.FEATURE_NAME }}</strong> feature branch.</p>" >> $HTML_FILE
            echo "    <p>Commit: <code>${{ github.sha }}</code></p>" >> $HTML_FILE
            echo "    <p>Last updated: <code>$(date)</code></p>" >> $HTML_FILE
            echo "  </div>" >> $HTML_FILE
            echo "  <h2>Available Resources</h2>" >> $HTML_FILE
            echo "  <ul>" >> $HTML_FILE
            echo "    <li><a href=\"CODAP-plugins/\">CODAP Plugins</a></li>" >> $HTML_FILE
            echo "  </ul>" >> $HTML_FILE
            echo "</body>" >> $HTML_FILE
            echo "</html>" >> $HTML_FILE
          fi
          
          echo "Preview content prepared at previews/${{ env.FEATURE_NAME }}:"
          ls -la previews/${{ env.FEATURE_NAME }}/

      - name: Commit and push changes to main
        run: |
          # Add the changes
          git add previews/${{ env.FEATURE_NAME }}
          
          # Only commit if there are changes
          if git status --porcelain | grep .; then
            # Create commit
            git commit -m "Deploy preview for ${{ env.FEATURE_NAME }} feature branch"
            
            # Push to main branch
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
            
            echo "✅ Successfully deployed preview to: https://chaddorsey.github.io/previews/${{ env.FEATURE_NAME }}/"
          else
            echo "No changes to commit."
          fi

      - name: Create index for all previews
        shell: bash
        run: |
          mkdir -p previews
          
          # Create the index.html file for all previews
          INDEX_FILE=previews/index.html
          echo "<!DOCTYPE html>" > $INDEX_FILE
          echo "<html lang=\"en\">" >> $INDEX_FILE
          echo "<head>" >> $INDEX_FILE
          echo "  <meta charset=\"UTF-8\">" >> $INDEX_FILE
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> $INDEX_FILE
          echo "  <title>Feature Branch Previews</title>" >> $INDEX_FILE
          echo "  <style>" >> $INDEX_FILE
          echo "    body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; max-width: 800px; margin: 0 auto; }" >> $INDEX_FILE
          echo "    h1 { color: #333; }" >> $INDEX_FILE
          echo "    .preview-list { list-style-type: none; padding: 0; }" >> $INDEX_FILE
          echo "    .preview-item { padding: 10px 15px; margin-bottom: 10px; background: #f8f9fa; border-left: 4px solid #007bff; }" >> $INDEX_FILE
          echo "    a { color: #007bff; text-decoration: none; }" >> $INDEX_FILE
          echo "    a:hover { text-decoration: underline; }" >> $INDEX_FILE
          echo "  </style>" >> $INDEX_FILE
          echo "</head>" >> $INDEX_FILE
          echo "<body>" >> $INDEX_FILE
          echo "  <h1>Feature Branch Previews</h1>" >> $INDEX_FILE
          echo "  <p>Select a feature branch preview to view:</p>" >> $INDEX_FILE
          echo "  <ul class=\"preview-list\">" >> $INDEX_FILE
          
          # List all preview directories and add them to the index
          for dir in previews/*/; do
            if [ -d "$dir" ] && [ "$dir" != "previews/index.html" ]; then
              preview_name=$(basename "$dir")
              echo "    <li class=\"preview-item\"><a href=\"$preview_name/\">$preview_name</a></li>" >> $INDEX_FILE
            fi
          done
          
          # Close the HTML file
          echo "  </ul>" >> $INDEX_FILE
          echo "  <p><em>Last updated: $(date)</em></p>" >> $INDEX_FILE
          echo "</body>" >> $INDEX_FILE
          echo "</html>" >> $INDEX_FILE
          
          # Add and commit the index
          git add previews/index.html
          git commit -m "Update previews index" || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main || true
          
          echo "✅ Previews index updated and available at: https://chaddorsey.github.io/previews/" 