# Deploy Feature Branch Preview
name: Deploy Feature Branch Preview

on:
  push:
    branches:
      - 'feature/*'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      # No build step needed since this is a simple JavaScript project with no build process
      # If you add a build process later, insert build steps here
      
      - name: Extract feature name
        id: extract
        run: echo "FEATURE_NAME=${GITHUB_REF#refs/heads/feature/}" >> $GITHUB_ENV

      - name: Debug Info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Feature name: $FEATURE_NAME"
          echo "Workspace: $GITHUB_WORKSPACE"
          du -sh .
          ls -la

      - name: Remove large files (if any)
        run: |
          # Example: Remove large data files that might cause issues
          find . -type f -size +50M -exec ls -lh {} \; || true
          find . -type f -name "*.zip" -size +50M -exec rm -f {} \; || true
          
      - name: Prepare for deployment
        run: |
          # Create a .gitignore file to exclude node_modules and other large files during deployment
          cat << EOF > .gitignore.deploy
          node_modules/
          **/node_modules/
          CODAP-plugins/Mini-tutorials/node_modules/
          **/attribute-selector-structure/
          **/.git
          **/.github
          EOF
          
          # Remove any existing node_modules directories that might still be tracked
          find . -type d -name "node_modules" -exec rm -rf {} \; 2>/dev/null || true
          
      - name: Prevent recursive path issues
        run: |
          # Remove attribute-selector-structure from the deployment to prevent recursive path issues
          if [ -d "attribute-selector-structure" ]; then
            echo "Found attribute-selector-structure directory, removing it from deployment"
            rm -rf attribute-selector-structure
          fi
          # Also check for any nested instances that could cause path length issues
          find . -type d -path "*attribute-selector-structure*attribute-selector-structure*" -exec rm -rf {} \; 2>/dev/null || true

      - name: Debug Git Info
        run: |
          echo "Git version:"
          git --version
          echo "Git config:"
          git config --list
          echo "Git status:"
          git status
          echo "Checking disk space:"
          df -h
          echo "Checking memory:"
          free -h || true

      - name: Deploy to gh-pages subfolder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Use a PAT with write access instead of GITHUB_TOKEN
          # Add this secret in your repository settings
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./
          branch: gh-pages
          target-folder: ${{ env.FEATURE_NAME }}
          clean: false
          clean-exclude: |
            attribute-selector-structure/**
          silent: false  # Disable silent mode to see more debug info
          single-commit: true  # Use a single commit - this is better for large repositories
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          commit-message: "Deploy branch ${{ env.FEATURE_NAME }} to GitHub Pages"